#!/bin/sh

case $1 in
  mac)
    ;;
  linux)
    ;;
  server)
    ;;
  *)
    echo "Invalid configuration."
    echo "Valid options:"
    echo "- $0 mac (sets up a Mac workstation)"
    echo "- $0 linux (sets up a Linux workstation)"
    echo "- $0 server (sets up a *nix server)"
    exit 1
esac

# First install brew on a mac
if [ `uname` = "Darwin" ]; then
  which brew &>/dev/null || \
    /usr/bin/ruby -e \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  # Install git and stow
  brew install git stow
elif [ -f "/etc/arch-release" ]; then
  sudo pacman -S --noconfirm git stow
elif [ `uname` = "FreeBSD" ]; then
  sudo pkg install git stow
fi

# Now that git is available let's check out or update our dotfiles
if [ -d ~/.dotfiles ]; then
  PREV=`pwd`
  cd ~/.dotfiles
  git pull
  cd $PREV
else
  git clone git@github.com:iantruslove/dotfiles.git ~/.dotfiles
fi

# Stow install our apps
~/.dotfiles/install $1

# Run the update
if [ "$1" = "mac" ]; then
  # TODO: Uncomment ### ~/bin/update
fi
