#!/usr/bin/env bash

# WORKSTATION_PACKAGES="emacs main node ruby tmux vim zsh" ## TODO: Fix and uncomment all of these
# SERVER_PACKAGES="bash main screen tmux vim" ## TODO: Fix and uncomment all of these
WORKSTATION_PACKAGES="bash main tmux zsh_arch"
SERVER_PACKAGES="bash main tmux"

STOW_DIR=~/.dotfiles  # `dirname $0`

pushd $STOW_DIR > /dev/null

case $1 in
    mac|linux)
        packages=$WORKSTATION_PACKAGES
    ;;
  server)
        packages=$SERVER_PACKAGES
        ;;
  *)
      echo "Invalid group"
      exit 1
    ;;
esac

for package in $packages; do
    echo -n "Stowing $package...  "
    output=$(stow -R $package 2>&1)
    result=$?
    if [ $result -eq 0 ]; then
        echo "ok"
    else
        echo "ERROR: $output"
    fi
done

popd
